<script setup lang="ts">
import { onMounted,ref } from 'vue'
import { listWarranties } from '../../api/content'
import ContentState from '../../components/content-state.vue'
import PrimaryPageIntro from '../../components/primary-page-intro.vue'
import type { WarrantySummary } from '../../types/domain'
const items=ref<WarrantySummary[]>([]),page=ref(1),hasMore=ref(true),loading=ref(false),status=ref<'loading'|'ready'|'empty'|'error'|'offline'>('loading'),message=ref('')
function date(value:number){const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
async function load(reset=false){if(loading.value)return;loading.value=true;if(reset){page.value=1;items.value=[];hasMore.value=true}try{const result=await listWarranties({page:page.value,pageSize:10});items.value=reset?result.items:[...items.value,...result.items];hasMore.value=result.items.length===10;status.value=items.value.length?'ready':'empty'}catch(e){const text=String((e as any)?.message||e);status.value=/network|offline|网络/i.test(text)?'offline':'error';message.value=status.value==='offline'?'网络已断开，请检查后重试':'质保服务加载失败'}finally{loading.value=false}}
function more(){if(hasMore.value){page.value+=1;load()}}
function open(id:string){uni.navigateTo({url:`/pages-sub/services/detail?id=${encodeURIComponent(id)}`})}
onMounted(()=>load(true))
</script>
<template><view class="page"><PrimaryPageIntro kicker="TEN-YEAR WARRANTY" title="十年质保服务" lead="真实验收、清晰期限，让长期服务有据可查"/><view class="promise"><text class="years">10</text><view><text class="heading">十年质保体系</text><text class="copy">仅展示已经竣工验收并由门店核验公开的项目。</text></view></view><ContentState v-if="status!=='ready'" :status="status" :message="status==='empty'?'暂无已公开的质保项目':message" @retry="load(true)"/><view v-else class="list"><view v-for="item in items" :key="item._id" class="card" hover-class="pressed" @click="open(item._id)"><image :src="item.cover_image" mode="aspectFill"/><view class="body"><view class="top"><text :class="['badge',item.warranty_status]">{{item.warranty_status==='active'?'质保中':'已过质保'}}</text><text>{{item.warranty_no}}</text></view><text class="title">{{item.title}}</text><text class="meta">{{item.district}} · 验收 {{date(item.accepted_at)}}</text><text class="expires">质保至 {{date(item.warranty_expires_at)}}</text></view></view><button v-if="hasMore" class="more" @click="more">加载更多</button><text v-else class="end">— 已展示全部质保项目 —</text></view></view></template>
<style scoped>.page{min-height:100vh;padding-bottom:calc(110rpx + env(safe-area-inset-bottom));background:#f4f6f4}.promise{display:flex;gap:28rpx;align-items:center;margin:30rpx;padding:34rpx;border-radius:22rpx;background:#fff}.years{font-family:Georgia,serif;color:#a57941;font-size:72rpx;font-weight:700}.heading,.copy,.title,.meta,.expires{display:block}.heading{color:#203832;font-size:30rpx;font-weight:650}.copy{margin-top:10rpx;color:#7b8883;font-size:23rpx;line-height:1.6}.list{display:flex;flex-direction:column;gap:24rpx;padding:0 30rpx}.card{overflow:hidden;border-radius:22rpx;background:#fff;box-shadow:0 10rpx 34rpx rgba(25,61,52,.08)}.pressed{transform:scale(.985)}.card image{display:block;width:100%;height:280rpx}.body{padding:25rpx}.top{display:flex;align-items:center;justify-content:space-between;color:#89958f;font-size:19rpx}.badge{padding:7rpx 14rpx;border-radius:20rpx}.active{color:#287354;background:#e2f2e9}.expired{color:#68756f;background:#edf0ee}.title{margin-top:17rpx;color:#183b32;font-size:31rpx;font-weight:650}.meta,.expires{margin-top:11rpx;color:#74827e;font-size:22rpx}.expires{color:#a57941}.more{border:1rpx solid #b9c8c3;border-radius:36rpx;color:#245c50;background:transparent}.more::after{border:0}.end{padding:20rpx;text-align:center;color:#99a5a1;font-size:22rpx}</style>
