<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { getServiceFilters, listServices } from '../../api/content'
import ContentState from '../../components/content-state.vue'
import PrimaryPageIntro from '../../components/primary-page-intro.vue'
import type { ServiceSummary } from '../../types/domain'
const STORE_ID='store_windoors_demo'
const typeOptions:Array<{label:string;value?:'construction'|'warranty'}>=[{label:'全部类型'},{label:'施工',value:'construction'},{label:'质保',value:'warranty'}]
const districts=ref<string[]>([]),districtIndex=ref(0),typeIndex=ref(0)
const items=ref<ServiceSummary[]>([]),page=ref(1),hasMore=ref(true),loading=ref(false),status=ref<'loading'|'ready'|'empty'|'error'|'offline'>('loading'),message=ref('')
function date(value?:number){if(!value)return '';const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function stageLabel(stage:string){return ({measuring:'测量中',designing:'设计中',installing:'安装中',completed:'已完工'} as Record<string,string>)[stage]||'施工'}
async function load(reset=false){if(loading.value)return;loading.value=true;if(reset){page.value=1;items.value=[];hasMore.value=true;status.value='loading'}try{const result=await listServices({storeId:STORE_ID,page:page.value,pageSize:10,district:districtIndex.value?districts.value[districtIndex.value-1]:undefined,type:typeOptions[typeIndex.value].value});items.value=reset?result.items:[...items.value,...result.items];hasMore.value=result.items.length===10;status.value=items.value.length?'ready':'empty'}catch(e){const text=String((e as any)?.message||e);status.value=/network|offline|网络/i.test(text)?'offline':'error';message.value=status.value==='offline'?'网络已断开，请检查后重试':'服务列表加载失败'}finally{loading.value=false}}
function more(){if(hasMore.value){page.value+=1;load()}}
function changeDistrict(event:{detail:{value:string}}){districtIndex.value=Number(event.detail.value);load(true)}
function changeType(event:{detail:{value:string}}){typeIndex.value=Number(event.detail.value);load(true)}
function open(id:string){uni.navigateTo({url:`/pages-sub/${items.value.find(item=>item._id===id)?.service_type==='warranty'?'services':'sites'}/detail?id=${encodeURIComponent(id)}`})}
onMounted(async()=>{try{districts.value=(await getServiceFilters(STORE_ID)).districts}finally{load(true)}})
</script>
<template><view class="page"><PrimaryPageIntro kicker="PROJECT SERVICE" title="施工与质保服务" lead="从现场施工到竣工质保，项目进度和服务期限清晰可查"/><view class="filters"><picker :range="['全部区域',...districts]" :value="districtIndex" @change="changeDistrict"><view class="filter">{{districtIndex?districts[districtIndex-1]:'全部区域'}}<text>⌄</text></view></picker><picker :range="typeOptions" range-key="label" :value="typeIndex" @change="changeType"><view class="filter">{{typeOptions[typeIndex].label}}<text>⌄</text></view></picker></view><ContentState v-if="status!=='ready'" :status="status" :message="status==='empty'?'暂无施工或质保项目':message" @retry="load(true)"/><view v-else class="list"><view v-for="item in items" :key="item._id" class="card" hover-class="pressed" @click="open(item._id)"><image :src="item.cover_image" mode="aspectFill"/><view class="body"><view class="top"><text :class="['badge',item.service_type]">{{item.service_type==='warranty'?(item.warranty_status==='active'?'质保中':'已过质保'):stageLabel(item.stage)}}</text><text>{{item.service_type==='warranty'?item.warranty_no:'施工'}}</text></view><text class="title">{{item.title}}</text><text class="meta">{{item.district}} · {{item.service_type==='warranty'?'验收 '+date(item.accepted_at):'项目施工中'}}</text><text v-if="item.service_type==='warranty'" class="expires">质保至 {{date(item.warranty_expires_at)}}</text></view></view><button v-if="hasMore" class="more" @click="more">加载更多</button><text v-else class="end">— 已展示全部项目 —</text></view></view></template>
<style scoped>.page{min-height:100vh;padding-bottom:calc(110rpx + env(safe-area-inset-bottom));background:#f4f6f4}.filters{display:flex;gap:18rpx;padding:25rpx 30rpx;position:sticky;top:0;z-index:2;background:rgba(244,246,244,.96)}.filters picker{flex:1}.filter{padding:20rpx 22rpx;border-radius:12rpx;color:#334b45;background:#fff;font-size:25rpx;box-shadow:0 5rpx 20rpx rgba(25,61,52,.05)}.filter text{float:right;color:#9ba7a3}.list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20rpx;padding:0 30rpx}.card{min-width:0;overflow:hidden;border-radius:16rpx;background:#fff;box-shadow:0 8rpx 24rpx rgba(25,61,52,.08)}.pressed{transform:scale(.985)}.card image{display:block;width:100%;height:210rpx}.body{padding:18rpx}.top{display:flex;align-items:center;justify-content:space-between;gap:8rpx;color:#89958f;font-size:17rpx}.top>text:last-child{overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.badge{flex:none;padding:6rpx 10rpx;border-radius:20rpx}.construction{color:#87602e;background:#f8ecd9}.warranty{color:#287354;background:#e2f2e9}.title{display:block;margin-top:13rpx;overflow:hidden;color:#183b32;font-size:27rpx;font-weight:650;white-space:nowrap;text-overflow:ellipsis}.meta,.expires{display:block;margin-top:9rpx;overflow:hidden;color:#74827e;font-size:20rpx;white-space:nowrap;text-overflow:ellipsis}.expires{color:#a57941}.more{grid-column:1 / -1;border:1rpx solid #b9c8c3;border-radius:36rpx;color:#245c50;background:transparent}.more::after{border:0}.end{grid-column:1 / -1;padding:20rpx;text-align:center;color:#99a5a1;font-size:22rpx}</style>
