<script setup lang="ts">
import { ref } from 'vue'
import { onLoad, onShareAppMessage, onShareTimeline } from '@dcloudio/uni-app'
import { getStaffProfile, getWarrantyDetail } from '../../api/content'
import ContentState from '../../components/content-state.vue'
import DetailActionBar from '../../components/detail-action-bar.vue'
import MediaGallery from '../../components/media-gallery.vue'
import type { SiteStage, StaffProfile, WarrantyDetail } from '../../types/domain'
import { classifyDetailError } from '../../utils/detail-state'
import { shareMessage, timelineMessage } from '../../utils/content-sharing'

const stageNames: Record<SiteStage, string> = { measuring: '测量复尺', designing: '方案设计', installing: '安装施工', completed: '竣工验收' }
const id = ref(''), item = ref<WarrantyDetail>(), staff = ref<StaffProfile[]>([]), status = ref<'loading'|'ready'|'empty'|'error'|'offline'>('loading'), message = ref('')
function date(value: number) { const d = new Date(value); return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日` }
async function load() { status.value = 'loading'; try { item.value = await getWarrantyDetail(id.value); const ids = [...new Set(item.value.updates.flatMap(update => update.staff_ids || []))]; const results = await Promise.allSettled(ids.map(getStaffProfile)); staff.value = results.flatMap(result => result.status === 'fulfilled' ? [result.value] : []); status.value = 'ready' } catch (e) { const f = classifyDetailError(e); status.value = f.status; message.value = f.retryable ? '质保详情加载失败' : '该质保内容已下架或不存在' } }
function updateStaff(ids: string[] = []) { return ids.map(id => staff.value.find(person => person._id === id)?.name).filter(Boolean).join('、') }
function call() { if (item.value?.store_phone) uni.makePhoneCall({ phoneNumber: item.value.store_phone }) }
function preview(src: string) { if (item.value) uni.previewImage({ current: src, urls: item.value.updates.flatMap(x => x.media) }) }
onLoad(q => { id.value = String(q?.id || ''); load() })
onShareAppMessage(() => item.value ? shareMessage('warranty', item.value._id, `十年质保：${item.value.title}`, item.value.cover_image) : {})
onShareTimeline(() => item.value ? timelineMessage(`十年质保：${item.value.title}`, item.value.cover_image) : {})
</script>

<template><view class="page"><ContentState v-if="status!=='ready'" :status="status" :message="message" @retry="load"/><template v-else-if="item"><image class="hero" :src="item.cover_image" mode="aspectFill"/><view class="panel headline"><text :class="['badge',item.warranty_status]">{{item.warranty_status==='active'?'质保中':'已过质保'}}</text><text class="title">{{item.title}}</text><text class="summary">{{item.summary}}</text><view class="facts"><text>{{item.district}}</text><text>{{item.area}}㎡</text><text>{{item.store_name}}</text></view></view><view class="panel warranty-certificate"><text class="section-title">十年质保凭证</text><view class="row"><text>质保编号</text><text>{{item.warranty_no}}</text></view><view class="row"><text>验收日期</text><text>{{date(item.accepted_at)}}</text></view><view class="row"><text>质保期限</text><text>{{date(item.accepted_at)}} 至 {{date(item.warranty_expires_at)}}</text></view><text class="description">{{item.warranty_description||'具体质保范围以门店确认的服务约定为准。'}}</text><button v-if="item.store_phone" class="call" @click="call">电话咨询质保服务</button></view><view class="panel"><text class="section-title">项目记录</text><view v-for="update in item.updates" :key="update._id" :class="['update',update.stage==='completed'?'completed':'']"><view class="update-meta"><text>{{date(update.occurred_at||update.created_at)}}</text><text>{{update.stage?stageNames[update.stage]:'施工记录'}}</text></view><text class="update-title">{{update.title}}</text><text class="description">{{update.content}}</text><view v-if="update.quality_tags?.length" class="quality-tags"><text v-for="tag in update.quality_tags" :key="tag">✓ {{tag}}</text></view><text v-if="update.next_step" class="next-step">下一步：{{update.next_step}}</text><MediaGallery :media="update.media" @preview="preview"/></view><text v-if="!item.updates.length" class="muted">暂无公开项目记录</text></view><DetailActionBar type="warranty" primary-label="电话咨询" :content-id="item._id" :title="item.title" :image="item.cover_image" :return-url="`/pages-sub/services/detail?id=${encodeURIComponent(item._id)}`" @appoint="call"/></template></view></template>

<style scoped>.page{min-height:100vh;padding-bottom:160rpx;background:#f1f4f2}.hero{width:100%;height:480rpx}.panel{margin:22rpx 26rpx;padding:30rpx;border-radius:22rpx;background:#fff}.warranty-certificate{color:#fff;background:linear-gradient(135deg,#24584c,#1b463b);box-shadow:0 12rpx 34rpx rgba(20,55,46,.12)}.warranty-certificate .section-title{color:#fff}.warranty-certificate .row{border-bottom-color:rgba(255,255,255,.16);color:rgba(255,255,255,.72)}.warranty-certificate .row text:last-child{color:#fff}.warranty-certificate .description{color:rgba(255,255,255,.78)}.warranty-certificate .call{color:#1b463b;background:#f1d9a7}.headline{position:relative;margin-top:-38rpx}.badge{display:inline-block;padding:8rpx 16rpx;border-radius:20rpx;font-size:22rpx}.active{color:#287354;background:#e2f2e9}.expired{color:#68756f;background:#edf0ee}.title{display:block;margin-top:16rpx;color:#183b32;font-size:38rpx;font-weight:650}.summary,.description{display:block;margin-top:14rpx;color:#687873;font-size:24rpx;line-height:1.7}.facts{display:flex;gap:24rpx;margin-top:20rpx;color:#31574d;font-size:22rpx}.section-title{display:block;margin-bottom:20rpx;color:#193c33;font-size:30rpx;font-weight:650}.row{display:flex;justify-content:space-between;gap:20rpx;padding:16rpx 0;border-bottom:1rpx solid #edf0ef;color:#61716b;font-size:23rpx}.row text:last-child{text-align:right;color:#263f38}.call{margin-top:24rpx;border:0;border-radius:38rpx;color:#fff;background:#24564a;font-size:25rpx}.call::after{border:0}.update{margin-top:16rpx;padding:22rpx;border-left:5rpx solid #b98646;border-radius:14rpx;background:#f7faf8}.update.completed{border-left-color:#287354;background:#edf7f1}.update-meta{display:flex;justify-content:space-between;color:#81918b;font-size:21rpx}.update-title{display:block;margin-top:12rpx;color:#294a42;font-size:26rpx;font-weight:600}.quality-tags{display:flex;flex-wrap:wrap;gap:10rpx;margin-top:16rpx}.quality-tags text{padding:7rpx 12rpx;border-radius:16rpx;color:#286451;background:#e1efe9;font-size:21rpx}.next-step{display:block;margin-top:16rpx;color:#a4773f;font-size:22rpx}.muted{color:#8c9995;font-size:23rpx}</style>
