<script setup lang="ts">
import { onLoad } from '@dcloudio/uni-app'
import { ref } from 'vue'
import { getProductDetail } from '../../api/content'
import ContentState from '../../components/content-state.vue'
import type { ProductDetail } from '../../types/domain'
import { classifyDetailError } from '../../utils/detail-state'
const id=ref(''),product=ref<ProductDetail>(),status=ref<'loading'|'ready'|'empty'|'error'|'offline'>('loading'),message=ref('')
async function load(){if(!id.value){status.value='empty';message.value='该产品不存在';return}status.value='loading';try{product.value=await getProductDetail(id.value);status.value='ready'}catch(error){const failure=classifyDetailError(error);status.value=failure.status;message.value=failure.retryable?'产品详情加载失败':'该产品已下架或不存在'}}
function appoint(){if(product.value)uni.navigateTo({url:`/pages-sub/appointments/create?source_type=product&source_id=${encodeURIComponent(product.value._id)}&store_id=${encodeURIComponent(product.value.store_id)}`})}
function consult(){uni.showModal({title:'联系客服',content:'请通过预约留下联系方式，我们会尽快联系您。',showCancel:false})}
onLoad((query:Record<string,string|undefined>)=>{id.value=query.id||'';load()})
</script>
<template><view class="page"><ContentState v-if="status!=='ready'" :status="status" :message="message" @retry="load"/><template v-else-if="product"><swiper class="hero" indicator-dots><swiper-item v-for="image in [product.cover_image,...product.gallery]" :key="image"><image :src="image" mode="aspectFill"/></swiper-item></swiper><view class="panel headline"><text class="kicker">PRODUCT DETAIL</text><text class="title">{{product.name}}</text><text class="summary">{{product.summary}}</text></view><view v-if="product.highlights.length" class="panel"><text class="section-title">产品亮点</text><view v-for="item in product.highlights" :key="item" class="line"><text class="dot"/>{{item}}</view></view><view v-if="product.specifications.length" class="panel"><text class="section-title">规格参数</text><view v-for="item in product.specifications" :key="item" class="spec">{{item}}</view></view><view v-if="product.scenarios.length" class="panel"><text class="section-title">适用场景</text><view class="tags"><text v-for="item in product.scenarios" :key="item">{{item}}</text></view></view></template><view v-if="status==='ready'" class="footer"><button class="secondary" @click="consult">电话咨询</button><button class="primary" @click="appoint">预约咨询</button></view></view></template>
<style scoped>.page{min-height:100vh;padding-bottom:150rpx;background:#f1f4f2}.hero,.hero image{width:100%;height:540rpx}.panel{margin:22rpx 26rpx;padding:32rpx;border-radius:20rpx;background:#fff}.headline{position:relative;margin-top:-38rpx}.kicker{display:block;color:#a4773f;font-size:19rpx;letter-spacing:3rpx}.title{display:block;margin-top:12rpx;color:#183b32;font-size:40rpx;font-weight:650}.summary{display:block;margin-top:16rpx;color:#687873;font-size:25rpx;line-height:1.7}.section-title{display:block;margin-bottom:22rpx;color:#193c33;font-size:31rpx;font-weight:650}.line{display:flex;align-items:center;gap:14rpx;padding:13rpx 0;color:#52655e;font-size:25rpx}.dot{width:10rpx;height:10rpx;border-radius:50%;background:#b98449}.spec{padding:17rpx 0;border-top:1rpx solid #edf0ef;color:#52655e;font-size:24rpx}.tags{display:flex;flex-wrap:wrap;gap:14rpx}.tags text{padding:12rpx 20rpx;border-radius:25rpx;background:#edf3f1;color:#31574d;font-size:23rpx}.footer{position:fixed;left:0;right:0;bottom:0;z-index:5;display:flex;gap:18rpx;padding:18rpx 26rpx calc(18rpx + env(safe-area-inset-bottom));background:#fff}.footer button{flex:1;border:0;border-radius:40rpx;font-size:27rpx}.footer button::after{border:0}.secondary{color:#24564a;background:#edf3f1}.primary{color:#fff;background:#24564a}</style>
