<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import UniDatetimePicker from '@dcloudio/uni-ui/lib/uni-datetime-picker/uni-datetime-picker.vue'
import { createSiteUpdateDraft, getSiteUpdateEditorOptions, uploadSiteUpdateImage, type EditableSite, type EditableStaff } from '../../api/site-update-editor'
import { getDemoPageBlock, showDemoUnavailable } from '../../config/demo-isolation'
import { isAuthFailure, loginUrl } from '../../utils/content-sharing'

const stages=[{value:'measuring',label:'测量复尺'},{value:'designing',label:'方案设计'},{value:'installing',label:'安装施工'},{value:'completed',label:'竣工验收'}]
const qualityOptions=['水平校准','密封检查','排水测试','启闭测试','玻璃检查','五金检查','成品保护','现场清洁']
const sites=ref<EditableSite[]>([]),staff=ref<EditableStaff[]>([]),loading=ref(true),saving=ref(false),uploading=ref(false),error=ref(''),privacyConfirmed=ref(false)
const demoBlock=getDemoPageBlock('施工动态管理')
const model=reactive({site_id:'',occurred_at:new Date(Date.now()+8*3600000).toISOString().slice(0,10),stage:'measuring',title:'',content:'',quality_tags:[] as string[],next_step:'',staff_ids:[] as string[],media:[] as string[]})
const selectedSite=computed(()=>sites.value.find(site=>site._id===model.site_id))
const availableStaff=computed(()=>staff.value.filter(person=>person.store_id===selectedSite.value?.store_id))
function stageChange(e:any){model.stage=stages[Number(e.detail.value)]?.value||'measuring';if(model.stage!=='completed')model.quality_tags=[]}
async function chooseImages(){
  if(showDemoUnavailable(uni,'施工图片上传'))return
  if(model.media.length>=9)return
  error.value=''
  try{uploading.value=true;const picked=await uni.chooseImage({count:9-model.media.length,sizeType:['compressed']});for(let i=0;i<picked.tempFilePaths.length;i++){const file:any=picked.tempFiles?.[i]||{};if(file.size>5*1024*1024)throw new Error('单张图片不能超过 5 MB');const path=picked.tempFilePaths[i];const ext=(path.split('.').pop()||'jpg').toLowerCase();if(!['jpg','jpeg','png','webp'].includes(ext))throw new Error('仅支持 JPG、PNG、WebP 图片');const result=await uploadSiteUpdateImage(path,`site-updates/${Date.now()}-${i}.${ext==='jpeg'?'jpg':ext}`);if(result.fileID)model.media.push(result.fileID)}}catch(e:any){if(!String(e?.errMsg||'').includes('cancel'))error.value=e?.message||e?.errMsg||'图片上传失败'}finally{uploading.value=false}
}
function removeImage(index:number){model.media.splice(index,1)}
async function save(){
  if(showDemoUnavailable(uni,'施工动态提交'))return
  error.value='';if(!model.site_id||!model.title.trim()||!model.content.trim()){error.value='请选择工地并填写标题和完成事项';return}if(!privacyConfirmed.value){error.value='请确认图片不包含客户隐私信息';return}
  saving.value=true;try{await createSiteUpdateDraft(model.site_id,{occurred_at:model.occurred_at,stage:model.stage,title:model.title,content:model.content,quality_tags:model.stage==='completed'?model.quality_tags:[],next_step:model.next_step,staff_ids:model.staff_ids,media:model.media});await uni.showModal({title:'已提交草稿',content:'施工动态不会立即公开，请在管理后台检查内容并发布。',showCancel:false});uni.navigateBack()}catch(e:any){error.value=e?.errMsg||e?.message||'提交失败'}finally{saving.value=false}
}
onLoad(async query=>{if(demoBlock){error.value=demoBlock;loading.value=false;return}try{const result=await getSiteUpdateEditorOptions();sites.value=result.sites||[];staff.value=result.staff||[];const requested=String(query?.site_id||'');model.site_id=sites.value.some(site=>site._id===requested)?requested:'';if(!model.site_id)error.value='当前工地不可记录施工动态'}catch(e:any){if(isAuthFailure(e)||e?.errCode==='UNAUTHORIZED')uni.redirectTo({url:loginUrl('/pages-sub/sites/update-create')});else error.value='当前账号没有施工记录权限'}finally{loading.value=false}})
</script>

<template><view class="page"><view class="intro"><text class="title">现场施工记录</text><text>工作人员提交后先保存为草稿，由管理员检查并发布。</text></view><view v-if="loading" class="card state">正在验证账号权限…</view><view v-else class="card"><view v-if="error" class="error">{{error}}</view><view class="field"><text>所属工地</text><view class="input readonly-input">{{selectedSite?.title||'当前工地不可用'}}</view></view><view class="grid"><view class="field"><text>施工日期</text><view class="date-picker-field"><UniDatetimePicker v-model="model.occurred_at" type="date" :clear-icon="false" /></view></view><view class="field"><text>施工阶段</text><picker :range="stages" range-key="label" @change="stageChange"><view class="input">{{stages.find(item=>item.value===model.stage)?.label}}<text>⌄</text></view></picker></view></view><view class="field"><text>记录标题</text><input v-model="model.title" class="input" placeholder="例如：完成窗框安装"/></view><view class="field"><text>完成事项</text><textarea v-model="model.content" class="textarea" placeholder="填写本次完成的施工内容和检查情况"/></view><view v-if="model.stage==='completed'" class="field"><text>质量检查</text><checkbox-group class="checks" @change="model.quality_tags=$event.detail.value"><label v-for="tag in qualityOptions" :key="tag"><checkbox :value="tag" color="#1f5a4d"/>{{tag}}</label></checkbox-group></view><view class="field"><text>下一步安排</text><input v-model="model.next_step" class="input" placeholder="选填"/></view><view v-if="availableStaff.length" class="field"><text>现场人员</text><checkbox-group class="checks" @change="model.staff_ids=$event.detail.value"><label v-for="person in availableStaff" :key="person._id"><checkbox :value="person._id" color="#1f5a4d"/>{{person.name}}</label></checkbox-group></view><view class="field"><view class="photo-heading"><text>现场图片（最多 9 张）</text><button :disabled="uploading" @click="chooseImages">{{uploading?'上传中…':'选择图片'}}</button></view><view class="photos"><view v-for="(image,index) in model.media" :key="image"><image :src="image" mode="aspectFill"/><text @click="removeImage(index)">删除</text></view></view></view><label class="privacy"><checkbox :checked="privacyConfirmed" color="#1f5a4d" @click="privacyConfirmed=!privacyConfirmed"/>我已确认图片不含客户姓名、电话、门牌号、证件、车牌及其他私密信息，并已取得必要展示授权。</label><button class="submit" :disabled="saving||uploading||!model.site_id" @click="save">{{saving?'提交中…':'提交草稿'}}</button></view></view></template>

<style scoped>.page{min-height:100vh;padding:28rpx;background:#f2f5f3}.intro{padding:30rpx 12rpx}.intro text{display:block;color:#74847e;font-size:23rpx}.intro .title{margin-bottom:10rpx;color:#183e34;font-size:38rpx;font-weight:700}.card{padding:30rpx;border-radius:24rpx;background:#fff}.state{text-align:center;color:#85928d}.error{margin-bottom:20rpx;padding:18rpx;border-radius:12rpx;color:#a8443d;background:#fff0ee}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18rpx}.field{margin-bottom:26rpx}.field>text,.photo-heading>text{display:block;margin-bottom:12rpx;color:#294a42;font-size:25rpx;font-weight:650}.input,.textarea{box-sizing:border-box;width:100%;border:1rpx solid #d9e2dd;border-radius:14rpx;background:#fafcfb;font-size:25rpx}.input{display:flex;align-items:center;justify-content:space-between;height:82rpx;padding:0 22rpx}.readonly-input{justify-content:flex-start;color:#52635d;background:#f1f3f1}.date-picker-field :deep(.uni-date-editor--x){box-sizing:border-box;min-height:82rpx;border-color:#d9e2dd!important;border-radius:14rpx;background:#fafcfb}.date-picker-field :deep(.uni-date__x-input){color:#263e37;font-size:25rpx}.textarea{height:190rpx;padding:20rpx}.checks{display:flex;flex-wrap:wrap;gap:14rpx}.checks label{padding:14rpx 18rpx;border:1rpx solid #dce4df;border-radius:14rpx;font-size:23rpx}.photo-heading{display:flex;align-items:center;justify-content:space-between}.photo-heading button{margin:0;border:0;border-radius:12rpx;color:#1f5a4d;background:#e5f0eb;font-size:22rpx}.photos{display:grid;grid-template-columns:repeat(3,1fr);gap:12rpx}.photos view{position:relative}.photos image{width:100%;height:180rpx;border-radius:12rpx}.photos text{position:absolute;right:6rpx;bottom:10rpx;padding:6rpx 12rpx;border-radius:18rpx;color:#fff;background:rgba(0,0,0,.58);font-size:20rpx}.privacy{display:flex;align-items:flex-start;gap:8rpx;margin:10rpx 0 30rpx;color:#687a73;font-size:22rpx;line-height:1.6}.submit{border:0;border-radius:40rpx;color:#fff;background:#1f5a4d;font-size:28rpx}.submit::after{border:0}@media(max-width:360px){.grid{grid-template-columns:1fr}}</style>
